version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./app/sql/local.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
      - ./conf/mysql/performance.cnf:/etc/mysql/conf.d/performance.cnf
    deploy:
      resources:
        limits:
          memory: 1G

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "127.0.0.1:8000:80" # Changes from 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: local
    volumes:
      - ./app/public:/var/www/html
      - ./conf/php/z-performance.ini:/usr/local/etc/php/conf.d/z-performance.ini
      - ./conf/apache-performance.conf:/etc/apache2/conf-enabled/z-performance.conf
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  db_data:
