<?php
if (!defined('ABSPATH')) {
    exit;
}
?>
<p class="form-field">
    <label for="_wt_coupon_format"><?php _e('Coupon format', 'wt-smart-coupons-for-woocommerce-pro'); ?></label>
    <span style="display:inline-block;">
        <input type="text" name="_wt_coupon_prefix" id="_wt_coupon_prefix" placeholder="<?php _e('Prefix', 'wt-smart-coupons-for-woocommerce-pro'); ?>" value="<?php echo esc_attr($coupon_settings['wt_coupon_prefix']); ?>" />
        <code>coupon_code</code>
        <input type="text" name="_wt_coupon_suffix" id="_wt_coupon_suffix" placeholder="<?php _e('Suffix', 'wt-smart-coupons-for-woocommerce-pro'); ?>" value="<?php echo esc_attr($coupon_settings['wt_coupon_suffix']); ?>" style="margin-right:0px;" />
    </span>
</p>
<p class="form-field">
    <label for="_wt_coupon_length">
        <?php _e('Length of the coupon code', 'wt-smart-coupons-for-woocommerce-pro'); ?>
    </label>
    <input type="text" name="_wt_coupon_length" id="_wt_coupon_length" placeholder="<?php _e('Length of the coupon code', 'wt-smart-coupons-for-woocommerce-pro'); ?>" value="<?php echo esc_attr($coupon_settings['no_of_characters_for_bulk_generate']); ?>" />
    <?php echo wc_help_tip( __('By default the plugin generates a 12 character coupon code minus the Prefix and Suffix.e.g,CRAZY-RTG23TYWE45Q-50, where CRAZY- is the prefix, RTG23TYWE45Q the autogenerated coupon code and -50 the suffix. ','wt-smart-coupons-for-woocommerce-pro') ); ?>
</p>